// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/omls/v1/fabric.proto

package omlsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Virt          string                 `protobuf:"bytes,3,opt,name=virt,proto3" json:"virt,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetVirt() string {
	if x != nil {
		return x.Virt
	}
	return ""
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type RegisterResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	HeartbeatIntervalMs int64                  `protobuf:"varint,2,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterResponse) GetHeartbeatIntervalMs() int64 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

type TelemetrySnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuLoad           float64                `protobuf:"fixed64,1,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"` // 0..N (loadavg-style or fraction*cores)
	MemAvailableBytes int64                  `protobuf:"varint,2,opt,name=mem_available_bytes,json=memAvailableBytes,proto3" json:"mem_available_bytes,omitempty"`
	MemTotalBytes     int64                  `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	TemperatureC      float64                `protobuf:"fixed64,4,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"` // 0 if unknown
	TemperatureKnown  bool                   `protobuf:"varint,5,opt,name=temperature_known,json=temperatureKnown,proto3" json:"temperature_known,omitempty"`
	ObservedUnixMs    int64                  `protobuf:"varint,6,opt,name=observed_unix_ms,json=observedUnixMs,proto3" json:"observed_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TelemetrySnapshot) Reset() {
	*x = TelemetrySnapshot{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySnapshot) ProtoMessage() {}

func (x *TelemetrySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySnapshot.ProtoReflect.Descriptor instead.
func (*TelemetrySnapshot) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{2}
}

func (x *TelemetrySnapshot) GetCpuLoad() float64 {
	if x != nil {
		return x.CpuLoad
	}
	return 0
}

func (x *TelemetrySnapshot) GetMemAvailableBytes() int64 {
	if x != nil {
		return x.MemAvailableBytes
	}
	return 0
}

func (x *TelemetrySnapshot) GetMemTotalBytes() int64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *TelemetrySnapshot) GetTemperatureC() float64 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *TelemetrySnapshot) GetTemperatureKnown() bool {
	if x != nil {
		return x.TemperatureKnown
	}
	return false
}

func (x *TelemetrySnapshot) GetObservedUnixMs() int64 {
	if x != nil {
		return x.ObservedUnixMs
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Telemetry     *TelemetrySnapshot     `protobuf:"bytes,3,opt,name=telemetry,proto3" json:"telemetry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetTelemetry() *TelemetrySnapshot {
	if x != nil {
		return x.Telemetry
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ReAdvertise   bool                   `protobuf:"varint,2,opt,name=re_advertise,json=reAdvertise,proto3" json:"re_advertise,omitempty"` // master wants a fresh profile
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetReAdvertise() bool {
	if x != nil {
		return x.ReAdvertise
	}
	return false
}

type AdvertiseProfileRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NodeId    string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// RDL Machine Profile encoded as YAML (preferred) or JSON.
	Format        string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // "yaml" | "json"
	Profile       []byte `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseProfileRequest) Reset() {
	*x = AdvertiseProfileRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseProfileRequest) ProtoMessage() {}

func (x *AdvertiseProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseProfileRequest.ProtoReflect.Descriptor instead.
func (*AdvertiseProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{5}
}

func (x *AdvertiseProfileRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AdvertiseProfileRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AdvertiseProfileRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AdvertiseProfileRequest) GetProfile() []byte {
	if x != nil {
		return x.Profile
	}
	return nil
}

type AdvertiseProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	ResourceCount int32                  `protobuf:"varint,2,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertiseProfileResponse) Reset() {
	*x = AdvertiseProfileResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertiseProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiseProfileResponse) ProtoMessage() {}

func (x *AdvertiseProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiseProfileResponse.ProtoReflect.Descriptor instead.
func (*AdvertiseProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{6}
}

func (x *AdvertiseProfileResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AdvertiseProfileResponse) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

type TelemetrySample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Snapshot      *TelemetrySnapshot     `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetrySample) Reset() {
	*x = TelemetrySample{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySample) ProtoMessage() {}

func (x *TelemetrySample) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySample.ProtoReflect.Descriptor instead.
func (*TelemetrySample) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{7}
}

func (x *TelemetrySample) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TelemetrySample) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TelemetrySample) GetSnapshot() *TelemetrySnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type TelemetryAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryAck) Reset() {
	*x = TelemetryAck{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryAck) ProtoMessage() {}

func (x *TelemetryAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryAck.ProtoReflect.Descriptor instead.
func (*TelemetryAck) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{8}
}

func (x *TelemetryAck) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{9}
}

type HealthResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ok"
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	NodeCount      int32                  `protobuf:"varint,3,opt,name=node_count,json=nodeCount,proto3" json:"node_count,omitempty"`
	AvailableNodes int32                  `protobuf:"varint,4,opt,name=available_nodes,json=availableNodes,proto3" json:"available_nodes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{10}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetNodeCount() int32 {
	if x != nil {
		return x.NodeCount
	}
	return 0
}

func (x *HealthResponse) GetAvailableNodes() int32 {
	if x != nil {
		return x.AvailableNodes
	}
	return 0
}

type GetGraphRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphRequest) Reset() {
	*x = GetGraphRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphRequest) ProtoMessage() {}

func (x *GetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetGraphRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{11}
}

type GetGraphResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource Graph dump as YAML.
	GraphYaml     []byte `protobuf:"bytes,1,opt,name=graph_yaml,json=graphYaml,proto3" json:"graph_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphResponse) Reset() {
	*x = GetGraphResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphResponse) ProtoMessage() {}

func (x *GetGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphResponse.ProtoReflect.Descriptor instead.
func (*GetGraphResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{12}
}

func (x *GetGraphResponse) GetGraphYaml() []byte {
	if x != nil {
		return x.GraphYaml
	}
	return nil
}

type ClaimWorkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimWorkRequest) Reset() {
	*x = ClaimWorkRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWorkRequest) ProtoMessage() {}

func (x *ClaimWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWorkRequest.ProtoReflect.Descriptor instead.
func (*ClaimWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{13}
}

func (x *ClaimWorkRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ClaimWorkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WorkUnit struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkId      string                 `protobuf:"bytes,1,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	Function    string                 `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`      // "parallel_workers"
	Iterations  int64                  `protobuf:"varint,3,opt,name=iterations,proto3" json:"iterations,omitempty"` // synthetic CPU burn size
	WorkerIndex int32                  `protobuf:"varint,4,opt,name=worker_index,json=workerIndex,proto3" json:"worker_index,omitempty"`
	WorkerCount int32                  `protobuf:"varint,5,opt,name=worker_count,json=workerCount,proto3" json:"worker_count,omitempty"` // total workers in this demo iteration
	// Optional Resource Envelope (YAML). Empty → agent default/balanced.
	EnvelopeYaml  []byte `protobuf:"bytes,6,opt,name=envelope_yaml,json=envelopeYaml,proto3" json:"envelope_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkUnit) Reset() {
	*x = WorkUnit{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkUnit) ProtoMessage() {}

func (x *WorkUnit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkUnit.ProtoReflect.Descriptor instead.
func (*WorkUnit) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{14}
}

func (x *WorkUnit) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *WorkUnit) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *WorkUnit) GetIterations() int64 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *WorkUnit) GetWorkerIndex() int32 {
	if x != nil {
		return x.WorkerIndex
	}
	return 0
}

func (x *WorkUnit) GetWorkerCount() int32 {
	if x != nil {
		return x.WorkerCount
	}
	return 0
}

func (x *WorkUnit) GetEnvelopeYaml() []byte {
	if x != nil {
		return x.EnvelopeYaml
	}
	return nil
}

type ClaimWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasWork       bool                   `protobuf:"varint,1,opt,name=has_work,json=hasWork,proto3" json:"has_work,omitempty"`
	Unit          *WorkUnit              `protobuf:"bytes,2,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimWorkResponse) Reset() {
	*x = ClaimWorkResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimWorkResponse) ProtoMessage() {}

func (x *ClaimWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimWorkResponse.ProtoReflect.Descriptor instead.
func (*ClaimWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{15}
}

func (x *ClaimWorkResponse) GetHasWork() bool {
	if x != nil {
		return x.HasWork
	}
	return false
}

func (x *ClaimWorkResponse) GetUnit() *WorkUnit {
	if x != nil {
		return x.Unit
	}
	return nil
}

type ReportWorkRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WorkId           string                 `protobuf:"bytes,3,opt,name=work_id,json=workId,proto3" json:"work_id,omitempty"`
	DurationMs       int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TempBeforeC      float64                `protobuf:"fixed64,5,opt,name=temp_before_c,json=tempBeforeC,proto3" json:"temp_before_c,omitempty"`
	TempAfterC       float64                `protobuf:"fixed64,6,opt,name=temp_after_c,json=tempAfterC,proto3" json:"temp_after_c,omitempty"`
	TemperatureKnown bool                   `protobuf:"varint,7,opt,name=temperature_known,json=temperatureKnown,proto3" json:"temperature_known,omitempty"`
	Error            string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportWorkRequest) Reset() {
	*x = ReportWorkRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportWorkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportWorkRequest) ProtoMessage() {}

func (x *ReportWorkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportWorkRequest.ProtoReflect.Descriptor instead.
func (*ReportWorkRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{16}
}

func (x *ReportWorkRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportWorkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportWorkRequest) GetWorkId() string {
	if x != nil {
		return x.WorkId
	}
	return ""
}

func (x *ReportWorkRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ReportWorkRequest) GetTempBeforeC() float64 {
	if x != nil {
		return x.TempBeforeC
	}
	return 0
}

func (x *ReportWorkRequest) GetTempAfterC() float64 {
	if x != nil {
		return x.TempAfterC
	}
	return 0
}

func (x *ReportWorkRequest) GetTemperatureKnown() bool {
	if x != nil {
		return x.TemperatureKnown
	}
	return false
}

func (x *ReportWorkRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReportWorkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportWorkResponse) Reset() {
	*x = ReportWorkResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportWorkResponse) ProtoMessage() {}

func (x *ReportWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportWorkResponse.ProtoReflect.Descriptor instead.
func (*ReportWorkResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{17}
}

func (x *ReportWorkResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type RunDemoRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Workers         int32                  `protobuf:"varint,1,opt,name=workers,proto3" json:"workers,omitempty"`                                           // total parallel workers
	Iterations      int32                  `protobuf:"varint,2,opt,name=iterations,proto3" json:"iterations,omitempty"`                                     // learning rounds
	WorkIterations  int64                  `protobuf:"varint,3,opt,name=work_iterations,json=workIterations,proto3" json:"work_iterations,omitempty"`       // CPU burn per worker unit
	ThermalCeilingC float64                `protobuf:"fixed64,4,opt,name=thermal_ceiling_c,json=thermalCeilingC,proto3" json:"thermal_ceiling_c,omitempty"` // 0 = default
	TimeoutMs       int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`                      // overall deadline
	// Optional Resource Envelope YAML applied to each work unit (OMLS 0.4).
	EnvelopeYaml []byte `protobuf:"bytes,6,opt,name=envelope_yaml,json=envelopeYaml,proto3" json:"envelope_yaml,omitempty"`
	// Scheduling policy: "ewma" (0.3 default) or "adaptive" (0.6 multi-signal).
	Policy        string `protobuf:"bytes,7,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunDemoRequest) Reset() {
	*x = RunDemoRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunDemoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDemoRequest) ProtoMessage() {}

func (x *RunDemoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDemoRequest.ProtoReflect.Descriptor instead.
func (*RunDemoRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{18}
}

func (x *RunDemoRequest) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *RunDemoRequest) GetIterations() int32 {
	if x != nil {
		return x.Iterations
	}
	return 0
}

func (x *RunDemoRequest) GetWorkIterations() int64 {
	if x != nil {
		return x.WorkIterations
	}
	return 0
}

func (x *RunDemoRequest) GetThermalCeilingC() float64 {
	if x != nil {
		return x.ThermalCeilingC
	}
	return 0
}

func (x *RunDemoRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *RunDemoRequest) GetEnvelopeYaml() []byte {
	if x != nil {
		return x.EnvelopeYaml
	}
	return nil
}

func (x *RunDemoRequest) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

type NodeAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Virt          string                 `protobuf:"bytes,3,opt,name=virt,proto3" json:"virt,omitempty"`
	Workers       int32                  `protobuf:"varint,4,opt,name=workers,proto3" json:"workers,omitempty"` // planned workers
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Executed      int32                  `protobuf:"varint,7,opt,name=executed,proto3" json:"executed,omitempty"` // work units actually completed on this node
	Function      string                 `protobuf:"bytes,8,opt,name=function,proto3" json:"function,omitempty"`  // function name when exclusive placement is used
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAllocation) Reset() {
	*x = NodeAllocation{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAllocation) ProtoMessage() {}

func (x *NodeAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAllocation.ProtoReflect.Descriptor instead.
func (*NodeAllocation) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{19}
}

func (x *NodeAllocation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeAllocation) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *NodeAllocation) GetVirt() string {
	if x != nil {
		return x.Virt
	}
	return ""
}

func (x *NodeAllocation) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *NodeAllocation) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *NodeAllocation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NodeAllocation) GetExecuted() int32 {
	if x != nil {
		return x.Executed
	}
	return 0
}

func (x *NodeAllocation) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

type DemoRound struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Round          int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Allocations    []*NodeAllocation      `protobuf:"bytes,2,rep,name=allocations,proto3" json:"allocations,omitempty"`
	DurationEwmaMs map[string]float64     `protobuf:"bytes,3,rep,name=duration_ewma_ms,json=durationEwmaMs,proto3" json:"duration_ewma_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	TempDeltaEwma  map[string]float64     `protobuf:"bytes,4,rep,name=temp_delta_ewma,json=tempDeltaEwma,proto3" json:"temp_delta_ewma,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	PolicyNote     string                 `protobuf:"bytes,5,opt,name=policy_note,json=policyNote,proto3" json:"policy_note,omitempty"`
	WallMs         int64                  `protobuf:"varint,6,opt,name=wall_ms,json=wallMs,proto3" json:"wall_ms,omitempty"`
	PlannedHosts   int32                  `protobuf:"varint,7,opt,name=planned_hosts,json=plannedHosts,proto3" json:"planned_hosts,omitempty"`    // hosts with workers > 0 in the plan
	ExecutedHosts  int32                  `protobuf:"varint,8,opt,name=executed_hosts,json=executedHosts,proto3" json:"executed_hosts,omitempty"` // hosts that actually completed work
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DemoRound) Reset() {
	*x = DemoRound{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoRound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoRound) ProtoMessage() {}

func (x *DemoRound) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoRound.ProtoReflect.Descriptor instead.
func (*DemoRound) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{20}
}

func (x *DemoRound) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *DemoRound) GetAllocations() []*NodeAllocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *DemoRound) GetDurationEwmaMs() map[string]float64 {
	if x != nil {
		return x.DurationEwmaMs
	}
	return nil
}

func (x *DemoRound) GetTempDeltaEwma() map[string]float64 {
	if x != nil {
		return x.TempDeltaEwma
	}
	return nil
}

func (x *DemoRound) GetPolicyNote() string {
	if x != nil {
		return x.PolicyNote
	}
	return ""
}

func (x *DemoRound) GetWallMs() int64 {
	if x != nil {
		return x.WallMs
	}
	return 0
}

func (x *DemoRound) GetPlannedHosts() int32 {
	if x != nil {
		return x.PlannedHosts
	}
	return 0
}

func (x *DemoRound) GetExecutedHosts() int32 {
	if x != nil {
		return x.ExecutedHosts
	}
	return 0
}

type RunDemoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rounds        []*DemoRound           `protobuf:"bytes,1,rep,name=rounds,proto3" json:"rounds,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunDemoResponse) Reset() {
	*x = RunDemoResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunDemoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunDemoResponse) ProtoMessage() {}

func (x *RunDemoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunDemoResponse.ProtoReflect.Descriptor instead.
func (*RunDemoResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{21}
}

func (x *RunDemoResponse) GetRounds() []*DemoRound {
	if x != nil {
		return x.Rounds
	}
	return nil
}

func (x *RunDemoResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ListProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesRequest) Reset() {
	*x = ListProfilesRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesRequest) ProtoMessage() {}

func (x *ListProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesRequest.ProtoReflect.Descriptor instead.
func (*ListProfilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{22}
}

type ProfileSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NodeId         string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Virt           string                 `protobuf:"bytes,3,opt,name=virt,proto3" json:"virt,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Samples        int32                  `protobuf:"varint,5,opt,name=samples,proto3" json:"samples,omitempty"`
	DurationEwmaMs float64                `protobuf:"fixed64,6,opt,name=duration_ewma_ms,json=durationEwmaMs,proto3" json:"duration_ewma_ms,omitempty"`
	Confidence     float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProfileSummary) Reset() {
	*x = ProfileSummary{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileSummary) ProtoMessage() {}

func (x *ProfileSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileSummary.ProtoReflect.Descriptor instead.
func (*ProfileSummary) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{23}
}

func (x *ProfileSummary) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ProfileSummary) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ProfileSummary) GetVirt() string {
	if x != nil {
		return x.Virt
	}
	return ""
}

func (x *ProfileSummary) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *ProfileSummary) GetSamples() int32 {
	if x != nil {
		return x.Samples
	}
	return 0
}

func (x *ProfileSummary) GetDurationEwmaMs() float64 {
	if x != nil {
		return x.DurationEwmaMs
	}
	return 0
}

func (x *ProfileSummary) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type ListProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*ProfileSummary      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	DataDir       string                 `protobuf:"bytes,2,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProfilesResponse) Reset() {
	*x = ListProfilesResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProfilesResponse) ProtoMessage() {}

func (x *ListProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProfilesResponse.ProtoReflect.Descriptor instead.
func (*ListProfilesResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{24}
}

func (x *ListProfilesResponse) GetProfiles() []*ProfileSummary {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ListProfilesResponse) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TelemetryTail int32                  `protobuf:"varint,2,opt,name=telemetry_tail,json=telemetryTail,proto3" json:"telemetry_tail,omitempty"` // last N samples; 0 = default 20
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{25}
}

func (x *GetProfileRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetProfileRequest) GetTelemetryTail() int32 {
	if x != nil {
		return x.TelemetryTail
	}
	return 0
}

type GetProfileResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProfileYaml    []byte                 `protobuf:"bytes,1,opt,name=profile_yaml,json=profileYaml,proto3" json:"profile_yaml,omitempty"`
	TelemetryJsonl []byte                 `protobuf:"bytes,2,opt,name=telemetry_jsonl,json=telemetryJsonl,proto3" json:"telemetry_jsonl,omitempty"` // optional tail as JSON lines
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_omls_v1_fabric_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_omls_v1_fabric_proto_rawDescGZIP(), []int{26}
}

func (x *GetProfileResponse) GetProfileYaml() []byte {
	if x != nil {
		return x.ProfileYaml
	}
	return nil
}

func (x *GetProfileResponse) GetTelemetryJsonl() []byte {
	if x != nil {
		return x.TelemetryJsonl
	}
	return nil
}

var File_proto_omls_v1_fabric_proto protoreflect.FileDescriptor

const file_proto_omls_v1_fabric_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/omls/v1/fabric.proto\x12\aomls.v1\"\x7f\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04virt\x18\x03 \x01(\tR\x04virt\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\"e\n" +
	"\x10RegisterResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\x15heartbeat_interval_ms\x18\x02 \x01(\x03R\x13heartbeatIntervalMs\"\x82\x02\n" +
	"\x11TelemetrySnapshot\x12\x19\n" +
	"\bcpu_load\x18\x01 \x01(\x01R\acpuLoad\x12.\n" +
	"\x13mem_available_bytes\x18\x02 \x01(\x03R\x11memAvailableBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x03 \x01(\x03R\rmemTotalBytes\x12#\n" +
	"\rtemperature_c\x18\x04 \x01(\x01R\ftemperatureC\x12+\n" +
	"\x11temperature_known\x18\x05 \x01(\bR\x10temperatureKnown\x12(\n" +
	"\x10observed_unix_ms\x18\x06 \x01(\x03R\x0eobservedUnixMs\"\x84\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x128\n" +
	"\ttelemetry\x18\x03 \x01(\v2\x1a.omls.v1.TelemetrySnapshotR\ttelemetry\"F\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fre_advertise\x18\x02 \x01(\bR\vreAdvertise\"\x83\x01\n" +
	"\x17AdvertiseProfileRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\fR\aprofile\"Q\n" +
	"\x18AdvertiseProfileResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12%\n" +
	"\x0eresource_count\x18\x02 \x01(\x05R\rresourceCount\"\x81\x01\n" +
	"\x0fTelemetrySample\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x126\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x1a.omls.v1.TelemetrySnapshotR\bsnapshot\"*\n" +
	"\fTelemetryAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\"\x0f\n" +
	"\rHealthRequest\"\x8a\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"node_count\x18\x03 \x01(\x05R\tnodeCount\x12'\n" +
	"\x0favailable_nodes\x18\x04 \x01(\x05R\x0eavailableNodes\"\x11\n" +
	"\x0fGetGraphRequest\"1\n" +
	"\x10GetGraphResponse\x12\x1d\n" +
	"\n" +
	"graph_yaml\x18\x01 \x01(\fR\tgraphYaml\"J\n" +
	"\x10ClaimWorkRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xca\x01\n" +
	"\bWorkUnit\x12\x17\n" +
	"\awork_id\x18\x01 \x01(\tR\x06workId\x12\x1a\n" +
	"\bfunction\x18\x02 \x01(\tR\bfunction\x12\x1e\n" +
	"\n" +
	"iterations\x18\x03 \x01(\x03R\n" +
	"iterations\x12!\n" +
	"\fworker_index\x18\x04 \x01(\x05R\vworkerIndex\x12!\n" +
	"\fworker_count\x18\x05 \x01(\x05R\vworkerCount\x12#\n" +
	"\renvelope_yaml\x18\x06 \x01(\fR\fenvelopeYaml\"U\n" +
	"\x11ClaimWorkResponse\x12\x19\n" +
	"\bhas_work\x18\x01 \x01(\bR\ahasWork\x12%\n" +
	"\x04unit\x18\x02 \x01(\v2\x11.omls.v1.WorkUnitR\x04unit\"\x8e\x02\n" +
	"\x11ReportWorkRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\awork_id\x18\x03 \x01(\tR\x06workId\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\"\n" +
	"\rtemp_before_c\x18\x05 \x01(\x01R\vtempBeforeC\x12 \n" +
	"\ftemp_after_c\x18\x06 \x01(\x01R\n" +
	"tempAfterC\x12+\n" +
	"\x11temperature_known\x18\a \x01(\bR\x10temperatureKnown\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"$\n" +
	"\x12ReportWorkResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\xfb\x01\n" +
	"\x0eRunDemoRequest\x12\x18\n" +
	"\aworkers\x18\x01 \x01(\x05R\aworkers\x12\x1e\n" +
	"\n" +
	"iterations\x18\x02 \x01(\x05R\n" +
	"iterations\x12'\n" +
	"\x0fwork_iterations\x18\x03 \x01(\x03R\x0eworkIterations\x12*\n" +
	"\x11thermal_ceiling_c\x18\x04 \x01(\x01R\x0fthermalCeilingC\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\x12#\n" +
	"\renvelope_yaml\x18\x06 \x01(\fR\fenvelopeYaml\x12\x16\n" +
	"\x06policy\x18\a \x01(\tR\x06policy\"\xd9\x01\n" +
	"\x0eNodeAllocation\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04virt\x18\x03 \x01(\tR\x04virt\x12\x18\n" +
	"\aworkers\x18\x04 \x01(\x05R\aworkers\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1a\n" +
	"\bexecuted\x18\a \x01(\x05R\bexecuted\x12\x1a\n" +
	"\bfunction\x18\b \x01(\tR\bfunction\"\x88\x04\n" +
	"\tDemoRound\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x129\n" +
	"\vallocations\x18\x02 \x03(\v2\x17.omls.v1.NodeAllocationR\vallocations\x12P\n" +
	"\x10duration_ewma_ms\x18\x03 \x03(\v2&.omls.v1.DemoRound.DurationEwmaMsEntryR\x0edurationEwmaMs\x12M\n" +
	"\x0ftemp_delta_ewma\x18\x04 \x03(\v2%.omls.v1.DemoRound.TempDeltaEwmaEntryR\rtempDeltaEwma\x12\x1f\n" +
	"\vpolicy_note\x18\x05 \x01(\tR\n" +
	"policyNote\x12\x17\n" +
	"\awall_ms\x18\x06 \x01(\x03R\x06wallMs\x12#\n" +
	"\rplanned_hosts\x18\a \x01(\x05R\fplannedHosts\x12%\n" +
	"\x0eexecuted_hosts\x18\b \x01(\x05R\rexecutedHosts\x1aA\n" +
	"\x13DurationEwmaMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a@\n" +
	"\x12TempDeltaEwmaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"W\n" +
	"\x0fRunDemoResponse\x12*\n" +
	"\x06rounds\x18\x01 \x03(\v2\x12.omls.v1.DemoRoundR\x06rounds\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"\x15\n" +
	"\x13ListProfilesRequest\"\xdc\x01\n" +
	"\x0eProfileSummary\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x12\n" +
	"\x04virt\x18\x03 \x01(\tR\x04virt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\asamples\x18\x05 \x01(\x05R\asamples\x12(\n" +
	"\x10duration_ewma_ms\x18\x06 \x01(\x01R\x0edurationEwmaMs\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\"f\n" +
	"\x14ListProfilesResponse\x123\n" +
	"\bprofiles\x18\x01 \x03(\v2\x17.omls.v1.ProfileSummaryR\bprofiles\x12\x19\n" +
	"\bdata_dir\x18\x02 \x01(\tR\adataDir\"S\n" +
	"\x11GetProfileRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0etelemetry_tail\x18\x02 \x01(\x05R\rtelemetryTail\"`\n" +
	"\x12GetProfileResponse\x12!\n" +
	"\fprofile_yaml\x18\x01 \x01(\fR\vprofileYaml\x12'\n" +
	"\x0ftelemetry_jsonl\x18\x02 \x01(\fR\x0etelemetryJsonl2\x85\x06\n" +
	"\x06Fabric\x12?\n" +
	"\bRegister\x12\x18.omls.v1.RegisterRequest\x1a\x19.omls.v1.RegisterResponse\x12B\n" +
	"\tHeartbeat\x12\x19.omls.v1.HeartbeatRequest\x1a\x1a.omls.v1.HeartbeatResponse\x12W\n" +
	"\x10AdvertiseProfile\x12 .omls.v1.AdvertiseProfileRequest\x1a!.omls.v1.AdvertiseProfileResponse\x12D\n" +
	"\x0fStreamTelemetry\x12\x18.omls.v1.TelemetrySample\x1a\x15.omls.v1.TelemetryAck(\x01\x129\n" +
	"\x06Health\x12\x16.omls.v1.HealthRequest\x1a\x17.omls.v1.HealthResponse\x12?\n" +
	"\bGetGraph\x12\x18.omls.v1.GetGraphRequest\x1a\x19.omls.v1.GetGraphResponse\x12B\n" +
	"\tClaimWork\x12\x19.omls.v1.ClaimWorkRequest\x1a\x1a.omls.v1.ClaimWorkResponse\x12E\n" +
	"\n" +
	"ReportWork\x12\x1a.omls.v1.ReportWorkRequest\x1a\x1b.omls.v1.ReportWorkResponse\x12<\n" +
	"\aRunDemo\x12\x17.omls.v1.RunDemoRequest\x1a\x18.omls.v1.RunDemoResponse\x12K\n" +
	"\fListProfiles\x12\x1c.omls.v1.ListProfilesRequest\x1a\x1d.omls.v1.ListProfilesResponse\x12E\n" +
	"\n" +
	"GetProfile\x12\x1a.omls.v1.GetProfileRequest\x1a\x1b.omls.v1.GetProfileResponseB7Z5github.com/Catatonic-Phobos/OMLS/proto/omls/v1;omlsv1b\x06proto3"

var (
	file_proto_omls_v1_fabric_proto_rawDescOnce sync.Once
	file_proto_omls_v1_fabric_proto_rawDescData []byte
)

func file_proto_omls_v1_fabric_proto_rawDescGZIP() []byte {
	file_proto_omls_v1_fabric_proto_rawDescOnce.Do(func() {
		file_proto_omls_v1_fabric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_omls_v1_fabric_proto_rawDesc), len(file_proto_omls_v1_fabric_proto_rawDesc)))
	})
	return file_proto_omls_v1_fabric_proto_rawDescData
}

var file_proto_omls_v1_fabric_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_proto_omls_v1_fabric_proto_goTypes = []any{
	(*RegisterRequest)(nil),          // 0: omls.v1.RegisterRequest
	(*RegisterResponse)(nil),         // 1: omls.v1.RegisterResponse
	(*TelemetrySnapshot)(nil),        // 2: omls.v1.TelemetrySnapshot
	(*HeartbeatRequest)(nil),         // 3: omls.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 4: omls.v1.HeartbeatResponse
	(*AdvertiseProfileRequest)(nil),  // 5: omls.v1.AdvertiseProfileRequest
	(*AdvertiseProfileResponse)(nil), // 6: omls.v1.AdvertiseProfileResponse
	(*TelemetrySample)(nil),          // 7: omls.v1.TelemetrySample
	(*TelemetryAck)(nil),             // 8: omls.v1.TelemetryAck
	(*HealthRequest)(nil),            // 9: omls.v1.HealthRequest
	(*HealthResponse)(nil),           // 10: omls.v1.HealthResponse
	(*GetGraphRequest)(nil),          // 11: omls.v1.GetGraphRequest
	(*GetGraphResponse)(nil),         // 12: omls.v1.GetGraphResponse
	(*ClaimWorkRequest)(nil),         // 13: omls.v1.ClaimWorkRequest
	(*WorkUnit)(nil),                 // 14: omls.v1.WorkUnit
	(*ClaimWorkResponse)(nil),        // 15: omls.v1.ClaimWorkResponse
	(*ReportWorkRequest)(nil),        // 16: omls.v1.ReportWorkRequest
	(*ReportWorkResponse)(nil),       // 17: omls.v1.ReportWorkResponse
	(*RunDemoRequest)(nil),           // 18: omls.v1.RunDemoRequest
	(*NodeAllocation)(nil),           // 19: omls.v1.NodeAllocation
	(*DemoRound)(nil),                // 20: omls.v1.DemoRound
	(*RunDemoResponse)(nil),          // 21: omls.v1.RunDemoResponse
	(*ListProfilesRequest)(nil),      // 22: omls.v1.ListProfilesRequest
	(*ProfileSummary)(nil),           // 23: omls.v1.ProfileSummary
	(*ListProfilesResponse)(nil),     // 24: omls.v1.ListProfilesResponse
	(*GetProfileRequest)(nil),        // 25: omls.v1.GetProfileRequest
	(*GetProfileResponse)(nil),       // 26: omls.v1.GetProfileResponse
	nil,                              // 27: omls.v1.DemoRound.DurationEwmaMsEntry
	nil,                              // 28: omls.v1.DemoRound.TempDeltaEwmaEntry
}
var file_proto_omls_v1_fabric_proto_depIdxs = []int32{
	2,  // 0: omls.v1.HeartbeatRequest.telemetry:type_name -> omls.v1.TelemetrySnapshot
	2,  // 1: omls.v1.TelemetrySample.snapshot:type_name -> omls.v1.TelemetrySnapshot
	14, // 2: omls.v1.ClaimWorkResponse.unit:type_name -> omls.v1.WorkUnit
	19, // 3: omls.v1.DemoRound.allocations:type_name -> omls.v1.NodeAllocation
	27, // 4: omls.v1.DemoRound.duration_ewma_ms:type_name -> omls.v1.DemoRound.DurationEwmaMsEntry
	28, // 5: omls.v1.DemoRound.temp_delta_ewma:type_name -> omls.v1.DemoRound.TempDeltaEwmaEntry
	20, // 6: omls.v1.RunDemoResponse.rounds:type_name -> omls.v1.DemoRound
	23, // 7: omls.v1.ListProfilesResponse.profiles:type_name -> omls.v1.ProfileSummary
	0,  // 8: omls.v1.Fabric.Register:input_type -> omls.v1.RegisterRequest
	3,  // 9: omls.v1.Fabric.Heartbeat:input_type -> omls.v1.HeartbeatRequest
	5,  // 10: omls.v1.Fabric.AdvertiseProfile:input_type -> omls.v1.AdvertiseProfileRequest
	7,  // 11: omls.v1.Fabric.StreamTelemetry:input_type -> omls.v1.TelemetrySample
	9,  // 12: omls.v1.Fabric.Health:input_type -> omls.v1.HealthRequest
	11, // 13: omls.v1.Fabric.GetGraph:input_type -> omls.v1.GetGraphRequest
	13, // 14: omls.v1.Fabric.ClaimWork:input_type -> omls.v1.ClaimWorkRequest
	16, // 15: omls.v1.Fabric.ReportWork:input_type -> omls.v1.ReportWorkRequest
	18, // 16: omls.v1.Fabric.RunDemo:input_type -> omls.v1.RunDemoRequest
	22, // 17: omls.v1.Fabric.ListProfiles:input_type -> omls.v1.ListProfilesRequest
	25, // 18: omls.v1.Fabric.GetProfile:input_type -> omls.v1.GetProfileRequest
	1,  // 19: omls.v1.Fabric.Register:output_type -> omls.v1.RegisterResponse
	4,  // 20: omls.v1.Fabric.Heartbeat:output_type -> omls.v1.HeartbeatResponse
	6,  // 21: omls.v1.Fabric.AdvertiseProfile:output_type -> omls.v1.AdvertiseProfileResponse
	8,  // 22: omls.v1.Fabric.StreamTelemetry:output_type -> omls.v1.TelemetryAck
	10, // 23: omls.v1.Fabric.Health:output_type -> omls.v1.HealthResponse
	12, // 24: omls.v1.Fabric.GetGraph:output_type -> omls.v1.GetGraphResponse
	15, // 25: omls.v1.Fabric.ClaimWork:output_type -> omls.v1.ClaimWorkResponse
	17, // 26: omls.v1.Fabric.ReportWork:output_type -> omls.v1.ReportWorkResponse
	21, // 27: omls.v1.Fabric.RunDemo:output_type -> omls.v1.RunDemoResponse
	24, // 28: omls.v1.Fabric.ListProfiles:output_type -> omls.v1.ListProfilesResponse
	26, // 29: omls.v1.Fabric.GetProfile:output_type -> omls.v1.GetProfileResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_omls_v1_fabric_proto_init() }
func file_proto_omls_v1_fabric_proto_init() {
	if File_proto_omls_v1_fabric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_omls_v1_fabric_proto_rawDesc), len(file_proto_omls_v1_fabric_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_omls_v1_fabric_proto_goTypes,
		DependencyIndexes: file_proto_omls_v1_fabric_proto_depIdxs,
		MessageInfos:      file_proto_omls_v1_fabric_proto_msgTypes,
	}.Build()
	File_proto_omls_v1_fabric_proto = out.File
	file_proto_omls_v1_fabric_proto_goTypes = nil
	file_proto_omls_v1_fabric_proto_depIdxs = nil
}
