// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/omls/v1/fabric.proto

package omlsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Fabric_Register_FullMethodName         = "/omls.v1.Fabric/Register"
	Fabric_Heartbeat_FullMethodName        = "/omls.v1.Fabric/Heartbeat"
	Fabric_AdvertiseProfile_FullMethodName = "/omls.v1.Fabric/AdvertiseProfile"
	Fabric_StreamTelemetry_FullMethodName  = "/omls.v1.Fabric/StreamTelemetry"
	Fabric_Health_FullMethodName           = "/omls.v1.Fabric/Health"
	Fabric_GetGraph_FullMethodName         = "/omls.v1.Fabric/GetGraph"
	Fabric_ClaimWork_FullMethodName        = "/omls.v1.Fabric/ClaimWork"
	Fabric_ReportWork_FullMethodName       = "/omls.v1.Fabric/ReportWork"
	Fabric_RunDemo_FullMethodName          = "/omls.v1.Fabric/RunDemo"
	Fabric_ListProfiles_FullMethodName     = "/omls.v1.Fabric/ListProfiles"
	Fabric_GetProfile_FullMethodName       = "/omls.v1.Fabric/GetProfile"
)

// FabricClient is the client API for Fabric service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Fabric is the OMLS control-plane API between agents, master, and operators.
type FabricClient interface {
	// Register joins a node into the Resource Graph.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Heartbeat refreshes liveness and optionally pushes light telemetry.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// AdvertiseProfile pushes (or refreshes) the node's RDL Machine Profile.
	AdvertiseProfile(ctx context.Context, in *AdvertiseProfileRequest, opts ...grpc.CallOption) (*AdvertiseProfileResponse, error)
	// StreamTelemetry is a client stream of samples (cpu/mem/temp/power).
	StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetrySample, TelemetryAck], error)
	// Health is a liveness probe for the master process.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// GetGraph dumps the current in-memory Resource Graph.
	GetGraph(ctx context.Context, in *GetGraphRequest, opts ...grpc.CallOption) (*GetGraphResponse, error)
	// ClaimWork lets an agent pull one work unit (empty if none).
	ClaimWork(ctx context.Context, in *ClaimWorkRequest, opts ...grpc.CallOption) (*ClaimWorkResponse, error)
	// ReportWork returns the result of a claimed work unit.
	ReportWork(ctx context.Context, in *ReportWorkRequest, opts ...grpc.CallOption) (*ReportWorkResponse, error)
	// RunDemo runs the 0.3 parallel_workers learning demo on the master.
	RunDemo(ctx context.Context, in *RunDemoRequest, opts ...grpc.CallOption) (*RunDemoResponse, error)
	// ListProfiles returns persisted Behavior Profiles (OMLS 0.5).
	ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error)
	// GetProfile returns one Behavior Profile and optional telemetry tail.
	GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error)
}

type fabricClient struct {
	cc grpc.ClientConnInterface
}

func NewFabricClient(cc grpc.ClientConnInterface) FabricClient {
	return &fabricClient{cc}
}

func (c *fabricClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Fabric_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, Fabric_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricClient) AdvertiseProfile(ctx context.Context, in *AdvertiseProfileRequest, opts ...grpc.CallOption) (*AdvertiseProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvertiseProfileResponse)
	err := c.cc.Invoke(ctx, Fabric_AdvertiseProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricClient) StreamTelemetry(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[TelemetrySample, TelemetryAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Fabric_ServiceDesc.Streams[0], Fabric_StreamTelemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetrySample, TelemetryAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fabric_StreamTelemetryClient = grpc.ClientStreamingClient[TelemetrySample, TelemetryAck]

func (c *fabricClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Fabric_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricClient) GetGraph(ctx context.Context, in *GetGraphRequest, opts ...grpc.CallOption) (*GetGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGraphResponse)
	err := c.cc.Invoke(ctx, Fabric_GetGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricClient) ClaimWork(ctx context.Context, in *ClaimWorkRequest, opts ...grpc.CallOption) (*ClaimWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimWorkResponse)
	err := c.cc.Invoke(ctx, Fabric_ClaimWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricClient) ReportWork(ctx context.Context, in *ReportWorkRequest, opts ...grpc.CallOption) (*ReportWorkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportWorkResponse)
	err := c.cc.Invoke(ctx, Fabric_ReportWork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricClient) RunDemo(ctx context.Context, in *RunDemoRequest, opts ...grpc.CallOption) (*RunDemoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunDemoResponse)
	err := c.cc.Invoke(ctx, Fabric_RunDemo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricClient) ListProfiles(ctx context.Context, in *ListProfilesRequest, opts ...grpc.CallOption) (*ListProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProfilesResponse)
	err := c.cc.Invoke(ctx, Fabric_ListProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fabricClient) GetProfile(ctx context.Context, in *GetProfileRequest, opts ...grpc.CallOption) (*GetProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfileResponse)
	err := c.cc.Invoke(ctx, Fabric_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FabricServer is the server API for Fabric service.
// All implementations must embed UnimplementedFabricServer
// for forward compatibility.
//
// Fabric is the OMLS control-plane API between agents, master, and operators.
type FabricServer interface {
	// Register joins a node into the Resource Graph.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Heartbeat refreshes liveness and optionally pushes light telemetry.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// AdvertiseProfile pushes (or refreshes) the node's RDL Machine Profile.
	AdvertiseProfile(context.Context, *AdvertiseProfileRequest) (*AdvertiseProfileResponse, error)
	// StreamTelemetry is a client stream of samples (cpu/mem/temp/power).
	StreamTelemetry(grpc.ClientStreamingServer[TelemetrySample, TelemetryAck]) error
	// Health is a liveness probe for the master process.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// GetGraph dumps the current in-memory Resource Graph.
	GetGraph(context.Context, *GetGraphRequest) (*GetGraphResponse, error)
	// ClaimWork lets an agent pull one work unit (empty if none).
	ClaimWork(context.Context, *ClaimWorkRequest) (*ClaimWorkResponse, error)
	// ReportWork returns the result of a claimed work unit.
	ReportWork(context.Context, *ReportWorkRequest) (*ReportWorkResponse, error)
	// RunDemo runs the 0.3 parallel_workers learning demo on the master.
	RunDemo(context.Context, *RunDemoRequest) (*RunDemoResponse, error)
	// ListProfiles returns persisted Behavior Profiles (OMLS 0.5).
	ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error)
	// GetProfile returns one Behavior Profile and optional telemetry tail.
	GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error)
	mustEmbedUnimplementedFabricServer()
}

// UnimplementedFabricServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFabricServer struct{}

func (UnimplementedFabricServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedFabricServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedFabricServer) AdvertiseProfile(context.Context, *AdvertiseProfileRequest) (*AdvertiseProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdvertiseProfile not implemented")
}
func (UnimplementedFabricServer) StreamTelemetry(grpc.ClientStreamingServer[TelemetrySample, TelemetryAck]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTelemetry not implemented")
}
func (UnimplementedFabricServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedFabricServer) GetGraph(context.Context, *GetGraphRequest) (*GetGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGraph not implemented")
}
func (UnimplementedFabricServer) ClaimWork(context.Context, *ClaimWorkRequest) (*ClaimWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimWork not implemented")
}
func (UnimplementedFabricServer) ReportWork(context.Context, *ReportWorkRequest) (*ReportWorkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportWork not implemented")
}
func (UnimplementedFabricServer) RunDemo(context.Context, *RunDemoRequest) (*RunDemoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunDemo not implemented")
}
func (UnimplementedFabricServer) ListProfiles(context.Context, *ListProfilesRequest) (*ListProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProfiles not implemented")
}
func (UnimplementedFabricServer) GetProfile(context.Context, *GetProfileRequest) (*GetProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedFabricServer) mustEmbedUnimplementedFabricServer() {}
func (UnimplementedFabricServer) testEmbeddedByValue()                {}

// UnsafeFabricServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FabricServer will
// result in compilation errors.
type UnsafeFabricServer interface {
	mustEmbedUnimplementedFabricServer()
}

func RegisterFabricServer(s grpc.ServiceRegistrar, srv FabricServer) {
	// If the following call pancis, it indicates UnimplementedFabricServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Fabric_ServiceDesc, srv)
}

func _Fabric_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabric_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabric_AdvertiseProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvertiseProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).AdvertiseProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_AdvertiseProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).AdvertiseProfile(ctx, req.(*AdvertiseProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabric_StreamTelemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FabricServer).StreamTelemetry(&grpc.GenericServerStream[TelemetrySample, TelemetryAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Fabric_StreamTelemetryServer = grpc.ClientStreamingServer[TelemetrySample, TelemetryAck]

func _Fabric_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabric_GetGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).GetGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_GetGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).GetGraph(ctx, req.(*GetGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabric_ClaimWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).ClaimWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_ClaimWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).ClaimWork(ctx, req.(*ClaimWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabric_ReportWork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportWorkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).ReportWork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_ReportWork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).ReportWork(ctx, req.(*ReportWorkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabric_RunDemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunDemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).RunDemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_RunDemo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).RunDemo(ctx, req.(*RunDemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabric_ListProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).ListProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_ListProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).ListProfiles(ctx, req.(*ListProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Fabric_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FabricServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Fabric_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FabricServer).GetProfile(ctx, req.(*GetProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fabric_ServiceDesc is the grpc.ServiceDesc for Fabric service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fabric_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "omls.v1.Fabric",
	HandlerType: (*FabricServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Fabric_Register_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _Fabric_Heartbeat_Handler,
		},
		{
			MethodName: "AdvertiseProfile",
			Handler:    _Fabric_AdvertiseProfile_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Fabric_Health_Handler,
		},
		{
			MethodName: "GetGraph",
			Handler:    _Fabric_GetGraph_Handler,
		},
		{
			MethodName: "ClaimWork",
			Handler:    _Fabric_ClaimWork_Handler,
		},
		{
			MethodName: "ReportWork",
			Handler:    _Fabric_ReportWork_Handler,
		},
		{
			MethodName: "RunDemo",
			Handler:    _Fabric_RunDemo_Handler,
		},
		{
			MethodName: "ListProfiles",
			Handler:    _Fabric_ListProfiles_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _Fabric_GetProfile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTelemetry",
			Handler:       _Fabric_StreamTelemetry_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/omls/v1/fabric.proto",
}
